#include <gtest/gtest.h>
#include "basecorrector.h"

TEST(BaseCorrectorTest, correctByOverlapAnalysis) {
    Read r1(new string("@name"),
        new string("TTTTAACCCCCCCCCCCCCCCCCCCCCCCCCCCCAATTTTAAAATTTTCCACGGGG"),
        new string("+"),
        new string("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEE"));
    Read r2(new string("@name"),
        new string("AAAAAAAAAACCCCGGGGAAAATTTTAAAATTGGGGGGGGGGTGGGGGGGGGGGGG"),
        new string("+"),
        new string("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEE"));

    BaseCorrector::correctByOverlapAnalysis(&r1, &r2, nullptr, 5, 30, 0.2);

    EXPECT_EQ(*r1.mSeq, "TTTTAACCCCCCCCCCCCCCCCCCCCCCCCCCCCAATTTTAAAATTTTCCCCGGGG");
    EXPECT_EQ(*r2.mSeq, "AAAAAAAAAACCCCGGGGAAAATTTTAAAATTGGGGGGGGGGGGGGGGGGGGGGGG");
    EXPECT_EQ(*r1.mQuality, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
    EXPECT_EQ(*r2.mQuality, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
}
